name: 构建和发布

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.head_commit && contains(github.event.head_commit.message, '[pub]') }}
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # js
      - name: Bun
        uses: oven-sh/setup-bun@v2

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Install dependencies
        run: bun i --frozen-lockfile

      # build
      - name: Change version
        id: set-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_DUR_RUN: true
        run: |
          OLD_VERSION="$(bun ./script/update-version.mts)"
          echo "old_version=$OLD_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          bun run build

      - name: Restore version
        run: |
          bun ./script/set-version.mts ${{ steps.set-version.outputs.old_version }}

      #publish
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec semantic-release